=== andreww2012/telegram-iv-parser/src/schema/schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/SiteSection",
  "definitions": {
    "SiteSection": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "options": {
          "$ref": "#/definitions/Options"
        },
        "stats": {
          "$ref": "#/definitions/Stats"
        },
        "pages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PageElement"
          }
        },
        "parsingResults": {
          "$ref": "#/definitions/ParsingResults"
        },
        "articles": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SiteSectionArticle"
          }
        }
      },
      "required": [
        "articles",
        "options",
        "pages",
        "parsingResults",
        "stats"
      ],
      "title": "SiteSection"
    },
    "SiteSectionArticle": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "hash": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "fromPage": {
          "type": "integer"
        },
        "code": {
          "type": "integer"
        },
        "parsingDates": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      },
      "required": [
        "code",
        "fromPage",
        "hash",
        "parsingDates",
        "url"
      ],
      "title": "SiteSectionArticle"
    },
    "Options": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "host": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "section": {
          "$ref": "#/definitions/Section"
        },
        "pagination": {
          "$ref": "#/definitions/Pagination"
        },
        "page": {
          "$ref": "#/definitions/OptionsPage"
        },
        "parsingStrategy": {
          "$ref": "#/definitions/ParsingStrategy"
        }
      },
      "required": [
        "host",
        "name",
        "page",
        "pagination",
        "parsingStrategy",
        "section"
      ],
      "title": "Options"
    },
    "OptionsPage": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "articleBodySelector": {
          "type": "string"
        },
        "ignoreSelectors": {
          "type": "array",
          "items": {}
        },
        "ignoreTags": {
          "type": "array",
          "items": {}
        },
        "preserveTags": {
          "type": "array",
          "items": {}
        },
        "ignoreClasses": {
          "type": "array",
          "items": {}
        },
        "preserveClasses": {
          "type": "array",
          "items": {}
        },
        "ignoreAttributes": {
          "type": "array",
          "items": {}
        },
        "preserveAttributes": {
          "type": "array",
          "items": {}
        }
      },
      "required": [
        "articleBodySelector",
        "ignoreAttributes",
        "ignoreClasses",
        "ignoreSelectors",
        "ignoreTags",
        "preserveAttributes",
        "preserveClasses",
        "preserveTags"
      ],
      "title": "OptionsPage"
    },
    "Pagination": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "totalNumberOfPagesSelector": {
          "type": "string"
        },
        "reversed": {
          "type": "boolean"
        },
        "enabled": {
          "type": "boolean"
        }
      },
      "required": [
        "enabled",
        "reversed",
        "totalNumberOfPagesSelector"
      ],
      "title": "Pagination"
    },
    "ParsingStrategy": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "__not_done_yet__": {
          "type": "boolean"
        }
      },
      "required": [
        "__not_done_yet__"
      ],
      "title": "ParsingStrategy"
    },
    "Section": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "pagePattern": {
          "type": "string"
        },
        "firstPageUrl": {
          "type": "string"
        },
        "linkSelector": {
          "type": "string"
        }
      },
      "required": [
        "firstPageUrl",
        "linkSelector",
        "pagePattern"
      ],
      "title": "Section"
    },
    "PageElement": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "num": {
          "type": "integer"
        },
        "articles": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PageArticle"
          }
        },
        "parsingDates": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      },
      "required": [
        "articles",
        "num",
        "parsingDates"
      ],
      "title": "PageElement"
    },
    "PageArticle": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "hash": {
          "type": "string"
        },
        "parsed": {
          "type": "boolean"
        }
      },
      "required": [
        "hash",
        "parsed"
      ],
      "title": "PageArticle"
    },
    "ParsingResults": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Attribute"
          }
        },
        "classes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Attribute"
          }
        },
        "attributes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Attribute"
          }
        },
        "unsupported": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Attribute"
          }
        }
      },
      "required": [
        "attributes",
        "classes",
        "tags",
        "unsupported"
      ],
      "title": "ParsingResults"
    },
    "Attribute": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "count": {
          "type": "integer"
        },
        "articles": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "articles",
        "count",
        "name"
      ],
      "title": "Attribute"
    },
    "Stats": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "pagesCount": {
          "type": "integer"
        },
        "fileGeneratedDate": {
          "type": "integer"
        },
        "parsingDates": {
          "type": "array",
          "items": {}
        }
      },
      "required": [
        "fileGeneratedDate",
        "pagesCount",
        "parsingDates"
      ],
      "title": "Stats"
    }
  }
}

=== andreww2012/telegram-iv-parser/src/schema/example.json
{
  "options": {
    "host": "test.ru",
    "name": "allnews",

    "section": {
      "pagePattern": "news/page/{0}.html",
      "firstPageUrl": "news",
      "linkSelector": ""
    },

    "pagination": {
      "totalNumberOfPagesSelector": "",
      "reversed": false,
      "enabled": true
    },

    "page": {
      "articleBodySelector": "",
      "ignoreSelectors": [],
      "ignoreTags": [],
      "preserveTags": [],
      "ignoreClasses": [],
      "preserveClasses": [],
      "ignoreAttributes": [],
      "preserveAttributes": []
    },

    "parsingStrategy": {
      "__not_done_yet__": true
    }
  },

  "stats": {
    "pagesCount": 0,
    "fileGeneratedDate": 0,
    "parsingDates": []
  },

  "pages": [
    {
      "num": 1,
      "articles": [
        {
          "hash": "articleHash1",
          "parsed": true
        }
      ],
      "parsingDates": [1552937372643, 1552937372642]
    }
  ],

  "parsingResults": {
    "tags": [
      {
        "name": "iframe",
        "count": 0,
        "articles": ["articleHash1", "articleHash2"]
      }
    ],
    "classes": [
      {
        "name": "test-class/h1",
        "count": 0,
        "articles": ["articleHash1", "articleHash2"]
      }
    ],
    "attributes": [
      {
        "name": "href/a",
        "count": 0,
        "articles": ["articleHash1", "articleHash2"]
      }
    ],
    "unsupported": [
      {
        "name": "aside/aside",
        "count": 0,
        "articles": ["articleHash1", "articleHash2"]
      }
    ]
  },

  "articles": [
    {
      "hash": "lGm8M6aggLbMjIHt",
      "url": "/news/test/123456789.html",
      "fromPage": 15,
      "code": 200,
      "parsingDates": [1552937372643, 1552937372642]
    }
  ]
}
